php: 
  build: .
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./www:/var/html
  links:
    - db

db:
  image: mysql:5.7
  volumes:
    - /var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=myrootpass
    - MYSQL_DATABASE=mydb